#!/usr/bin/env python3
"""Turn G06_Device_Scripts/*.txt (HSRP set) and C9200L-VRRP/*.txt (VRRP set) into data/configs.js.
Run again whenever the txt scripts change:  python3 build.py
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "G06_Device_Scripts")
SETS = {"hsrp": SRC, "vrrp": os.path.join(SRC, "C9200L-VRRP")}
DEVICES = ["CE01", "CE02", "MLS01", "MLS02", "R01", "SW01"]
WEB_HOSTNAMES = {d: f"G06-{'BR' if d in ('R01', 'SW01') else 'HQ'}-{d}" for d in DEVICES}
MARK = re.compile(r"^! -{3,} (.*?) -{3,}\s*$")


def strip(line):
    return re.sub(r"^!\s?", "", line).rstrip()


def public_command(line, path):
    """Keep the shared website free of literal credentials and lab key hashes."""
    # Use worksheet hostnames in website copies; leave the source TXT untouched.
    hostname = re.match(r"^(\s*hostname\s+)\S+\s*$", line)
    if hostname:
        device = os.path.splitext(os.path.basename(path))[0]
        return hostname.group(1) + WEB_HOSTNAMES[device]
    if re.match(r"^\s*(?:enable secret|username\b.*\bsecret)\s", line):
        if not re.search(r"<[^>]+>", line):
            raise ValueError(f"{path}: replace the credential with a placeholder before generating the website")
    key = re.match(r"^(\s*key-hash\s+\S+\s+)(\S+)(.*)$", line)
    if key and not re.search(r"<[^>]+>", key.group(2)):
        return key.group(1) + "<SSH_PUBLIC_KEY_HASH>" + key.group(3)
    return line


def parse(path):
    lines = open(path, encoding="utf-8").read().splitlines()
    header, prelude, blocks, untested_intro = [], [], [], []
    cur, section, in_verify = None, "tested", False
    for raw in lines:
        line = raw.rstrip()
        if "ยังไม่ทดสอบบน RACK" in line:
            section, cur, in_verify = "untested", None, False
            continue
        m = MARK.match(line)
        if m:
            title = m.group(1).strip()
            kind = "verify" if title.startswith("ตรวจ") else "config"
            status = section
            if section == "untested" and "ผ่านบน Rack" in title:
                status = "passed"
            title = title.replace("[ยังไม่ทดสอบ] ", "")
            cur = {"title": title, "kind": kind, "status": status, "notes": [], "commands": [], "verify": []}
            blocks.append(cur)
            in_verify = False
            continue
        if cur is None:
            if not line.strip() or set(line.strip()) <= {"!", "="} or line.startswith("! ====="):
                continue
            if line.startswith("!"):
                (untested_intro if section == "untested" else header).append(strip(line))
            else:
                prelude.append(line)
            continue
        if not line.strip() or line.strip() == "!":
            in_verify = False
            continue
        if line.startswith("!"):
            text = strip(line)
            if cur["kind"] == "verify":
                (cur["verify"] if not text.startswith(("ยังไม่ทำ", "PC Branch", "SW01 เข้า")) else cur["notes"]).append(text)
            elif text.startswith("ตรวจ:"):
                cur["verify"].append(text[len("ตรวจ:"):].strip()); in_verify = True
            elif in_verify and raw.startswith("!       "):
                cur["verify"].append(text.strip())
            else:
                cur["notes"].append(text); in_verify = False
        else:
            cur["commands"].append(public_command(line, path))
    return {"header": [h for h in header if h], "prelude": prelude, "blocks": blocks,
            "untestedIntro": [u for u in untested_intro if u]}


out = {}
for key, folder in SETS.items():
    out[key] = {d: parse(os.path.join(folder, f"{d}.txt")) for d in DEVICES}
js = "// generated by build.py from G06_Device_Scripts — do not edit by hand\nwindow.G06_CONFIGS = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n"
open(os.path.join(HERE, "data", "configs.js"), "w", encoding="utf-8").write(js)
for key in out:
    print(key, {d: len(out[key][d]["blocks"]) for d in DEVICES})
